Protocols = [
        "Dim_reductions",
    ]

Parameters_ID = "v1_l"

[Dim_reductions]
morphoframe_filepath = false
# Name of the mrophoframe that contains the vectors to dim reduce
"morphoframe_name" = "v1_pi_pca_umap"

# the name of the column in morphoframe that contains the vectors to dim reduce
"vectors_to_reduce" = 'pipcaselected'
# a function that put to 0 the value of pixel that exeed a certain value computed by the std of the image
"filter_pixels" = false
#
"normalize" = false
#
"standardize" = false

"save_data" = false
# "save_folderpath" = "results/umap"

"save_dimreducer" = false

    [Dim_reductions.dimred_method_parameters]                 
                                
        [Dim_reductions.dimred_method_parameters.umap]
        # parameters for umap
        "n_components" = 2
        "n_neighbors" = 50 
        "min_dist" = 0.1
        "spread" = 3.0
        "random_state" = 10
        "metric" = "euclidean"
        "densmap" = false